title: Khushi Gajjar
description: >
  A Computer Engineering student with a strong foundation in programming, machine learning, and data science. 
  Showcasing expertise in NLP, computer vision, data analytics, academic research, and innovative projects.
show_downloads: true
theme: jekyll-theme-hacker

author:
  name: Khushi Gajjar
  location: India
  email: khushigajjar456@gmail.com
  linkedin: khushi-gajjar1
  github: khushimgajjar
  twitter: "_Khushi_20"
  kaggle: khushikhushikhushi
